[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
linker = "musl-gcc"
rustflags = [
    "-C", "llvm-args=-function-sections -data-sections",
    "-C", "link-arg=-Wl,--gc-sections",
]
